# Generated by Django 4.1 on 2022-09-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(default=0, max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=0, max_length=255)),
                ('is_cod', models.BooleanField(default=False)),
                ('package', models.ManyToManyField(to='tutorial.package')),
            ],
        ),
    ]
